Запрос на проверку задачи "Список дисциплин" (Issue-49)
YuriSilenok/self-checking pull request #57
Opened 2021-08-06 06:05 UTC by ValeriSavvva

_Проверьте пожалуйста_

2021-08-09 11:26 UTC, YuriSilenok reviewed
На UI текст в ячейках таблицы воровнен по левому краю, в врествке по центру
![image](https://user-images.githubusercontent.com/14871471/128699146-0b80c4e5-beba-4304-9a81-f70911ac229a.png)

2021-08-09 12:20 UTC, YuriSilenok reviewed
Обратил внимание что этот UI не предусматривает сообщения в случае, если преподаватель еще не создавал ни одной дисциплины. Так и должно быть?

2021-08-09 12:23 UTC, YuriSilenok commented
запросы на проверку не нужно выбрасывать на доску, они линкукуются с задачами я являются частью задач.

2021-08-10 10:39 UTC, ValeriSavvva commented
@Nastasitze

2021-08-10 12:59 UTC, Nastasitze submitted a review, later dismissed
allright

2021-08-10 13:46 UTC, YuriSilenok requested changes
Давай договоримся использовать вот [этот](https://www.freeformatter.com/css-beautifier.html#ad-output) онлайн форматтер, пока я не найду более элегантное решение для контроля форматирования файлов css

2021-08-10 13:46 UTC, YuriSilenok commented on templates/discipline.html
> +    Вверхняя панель поможет вам это сделать.</div>
`Вверхняя` - опечатка

2021-08-10 13:46 UTC, YuriSilenok commented on templates/solving.html
> +    <div class="table tree-columns">
почему мы здесь что-то меняли?

2021-08-10 13:46 UTC, YuriSilenok commented on templates/solving.html
> +    <div class="notification mini-form no-visible">На данный момент работы, требующей вашей проверки, нет. Отдыхайте.</div>
и здесь что-то поменяли?

2021-08-10 13:50 UTC, ValeriSavvva commented on templates/solving.html
> +    <div class="notification mini-form no-visible">На данный момент работы, требующей вашей проверки, нет. Отдыхайте.</div>
разделила классы правильнее, потому что мини форма требуется без класса notification

2021-08-10 13:50 UTC, ValeriSavvva commented on templates/solving.html
> +    <div class="table tree-columns">
Потому что таблицы будут не только в три столбца

2021-08-10 13:51 UTC, ValeriSavvva commented on templates/discipline.html
> +    Вверхняя панель поможет вам это сделать.</div>
хорошо!

2021-08-11 13:16 UTC, YuriSilenok commented on templates/discipline.html
> +    Вверхняя панель поможет вам это сделать.</div>
так гдн еоммит с исправлением?

2021-08-11 13:45 UTC, YuriSilenok commented
@ValeriSavvva а еще я тебя поздравляю, из-за того, что ты влезла в файлы не в рамках задачи, у тебя случился конфликт.

2021-09-01 15:47 UTC, merged