Верстка "Список задач"
YuriSilenok/self-checking pull request #66
Opened 2021-09-02 15:08 UTC by ValeriSavvva

Был изменен Html файл "task".

2021-09-03 16:45 UTC, YuriSilenok commented on templates/task.html
> +                        <input class="textbox text-on-white little" type="text" name="review_count" id="review_count">
@Nastasitze мы в это поле можем добавлять что угодно?
@ValeriSavvva кто ограничения ввода данных будет реализовывать?
@ValeriSavvva почему мы @Nastasitze  не привлекаем к проверке, она не может проверить соответсвие верстки требованим?

2021-09-06 16:32 UTC, YuriSilenok requested changes
@ValeriSavvva почему тольбко я проверю верстку?

2021-09-06 16:32 UTC, YuriSilenok commented on templates/task.html
> +        <div class="mini-form notification after-add">На данный момент не создано ни одного задания</div>
На UI выравнивание по центру, здесь по левому краю.

2021-09-06 16:34 UTC, ValeriSavvva commented
> @ValeriSavvva почему только я проверю верстку?

Вы мне больше нравитесь

2021-09-06 16:41 UTC, YuriSilenok commented
> > @ValeriSavvva почему только я проверю верстку?
> 
> Вы мне больше нравитесь

Вот на гитхабе мне еще в этом не признавались.

2021-09-06 16:46 UTC, YuriSilenok commented
> > @ValeriSavvva почему только я проверю верстку?
> 
> Вы мне больше нравитесь

кстати, давно "любовных" записок не было

2021-09-06 16:51 UTC, YuriSilenok commented on templates/task.html
> +        <div class="mini-form notification after-add">На данный момент не создано ни одного задания</div>
Интересно, а почему текст не совпадает с UI?

2021-09-06 16:54 UTC, YuriSilenok reviewed
вот [тут](https://github.com/YuriSilenok/self-checking/pull/66#discussion_r703010808) проблема

2021-09-06 17:12 UTC, YuriSilenok reviewed
Почему пулл реквест на доске оказался?

2021-09-06 17:15 UTC, YuriSilenok requested changes
еще в US/UX/UI не нашел сведений о том, какое должно быть сообщение

2021-09-06 18:35 UTC, ValeriSavvva commented
> еще в US/UX/UI не нашел сведений о том, какое должно быть сообщение

Не понял

2021-09-06 19:14 UTC, YuriSilenok approved these changes

2021-09-07 11:44 UTC, merged