Верстка "Список тем".
YuriSilenok/self-checking pull request #67
Opened 2021-09-02 17:33 UTC by ValeriSavvva

Был изменен Html файл "theme"

2021-09-06 11:38 UTC, YuriSilenok requested changes
Вероятно следует изменить UI и UX

2021-09-06 11:38 UTC, YuriSilenok commented on templates/theme.html
> +            <div class="col">{{ discipline.name }}</div>
В макете выравнивание по левому краю, где правильно?

2021-09-06 11:38 UTC, YuriSilenok commented on templates/theme.html
> +                        <option disabled selected>Группа</option>
В макете указана дисциплина, где правильно?

2021-09-06 14:58 UTC, ValeriSavvva commented on templates/theme.html
> +                        <option disabled selected>Группа</option>
не поняла

2021-09-06 15:43 UTC, ValeriSavvva commented on templates/theme.html
> +                        <option disabled selected>Группа</option>
Ну в UI не указана Дисциплина и никто ничего не сказал

2021-09-06 16:38 UTC, YuriSilenok commented on templates/theme.html
> +                        <option disabled selected>Группа</option>
да, не дисциплина, а задача. 
![image](https://user-images.githubusercontent.com/14871471/132245589-c9cc3dc1-daad-4c77-aa48-71f112a8778c.png)

2021-09-06 16:48 UTC, ValeriSavvva commented on templates/theme.html
> +                        <option disabled selected>Группа</option>
не понимаю, жду видеосообщение в телеграмме, что не так, где вы пальцем тыкнете по экрану

2021-09-06 16:58 UTC, YuriSilenok commented on templates/theme.html
> +                        <option disabled selected>Группа</option>
![132245589-c9cc3dc1-daad-4c77-aa48-71f112a8778c (1)](https://user-images.githubusercontent.com/14871471/132247064-6b31ea44-820e-45da-818b-6f6d93aaef95.png)

2021-09-06 16:59 UTC, ValeriSavvva commented on templates/theme.html
> +                        <option disabled selected>Группа</option>
Там вообще группа

2021-09-06 16:59 UTC, ValeriSavvva commented on templates/theme.html
> +                        <option disabled selected>Группа</option>
И в верстке написано группа

2021-09-06 17:17 UTC, YuriSilenok commented on templates/theme.html
> +                        <option disabled selected>Группа</option>
Так вот, нужно устранить расхождение.

2021-09-06 19:01 UTC, YuriSilenok reviewed
[Посмотри](https://github.com/YuriSilenok/self-checking/pull/67#discussion_r702832736) пожалуйста внимательнее, еще не всё исправлено

2021-09-07 15:08 UTC, ValeriSavvva commented on templates/theme.html
> +            <div class="col">{{ discipline.name }}</div>
@YuriSilenok UI/UX исправлено, теперь все соответствует

2021-09-15 16:40 UTC, Nastasitze commented
К формулировкам текстовых фрагментов и к расположению блоков (header/ add student/ list of themes) вопросов нет

2021-09-15 16:41 UTC, Nastasitze submitted a review, later dismissed
All ok

2021-09-15 17:47 UTC, YuriSilenok requested changes
PR не должно быть на доске

2021-09-16 17:41 UTC, ValeriSavvva commented
> PR не должно быть на доске

что такое PR

2021-09-17 07:34 UTC, YuriSilenok commented
> > PR не должно быть на доске
> 
> что такое PR

Pull Request

2021-09-30 07:30 UTC, YuriSilenok approved these changes

2021-10-05 17:37 UTC, Nastasitze approved these changes
모든 것이 괜찮습니다.

2021-10-05 17:38 UTC, merged

2021-10-06 07:05 UTC, YuriSilenok commented
> 모든 것이 괜찮습니다

![image](https://user-images.githubusercontent.com/14871471/136155786-98471969-493c-40c4-b370-d0fdac4c4ed8.png)